In [1]:
import pandas as pd

In [2]:
data_dictionary = pd.read_csv('./Data_dictionary.csv')

In [4]:
data_dictionary[data_dictionary['Unnamed: 13'] == 'Yes']

,Unnamed: 0.1,Unnamed: 0,Unnamed: 1,Unnamed: 2,Missing values,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
16,16,score_MAT,Student scores,Continuous,0.08179148,0.10028487,0.0193629,0.02625888,0.20019157,0.04285714,0.02817328,0.23488301,0.04497608,0.26085681,Yes,Yes,No,Score in Mathematics
17,17,level_MAT,Student scores,Categorical,0.08179148,0.10028487,0.0193629,0.02625888,0.20019157,0.04285714,0.02817328,0.23488301,0.04497608,0.26085681,Yes,Yes,No,Proficiency levels in Mathematics
18,18,score_LEN,Student scores,Continuous,0.080372,0.09487712,0.02061212,0.02811245,0.07790549,0.04012158,0.0212057,0.06381039,0.0452279,0.09242958,Yes,Yes,No,Score in Spanish Language
19,19,level_LEN,Student scores,Categorical,0.080372,0.09487712,0.02061212,0.02811245,0.07790549,0.04012158,0.0212057,0.06381039,0.0452279,0.09242958,Yes,Yes,No,Proficiency levels in Spanish Language
20,20,score_ING,Student scores,Continuous,1,0.09647047,1,0.03521779,0.12132822,1,0.02453802,0.09358857,0.04417023,0.11766432,Yes,Yes,No,Score in English
21,21,level_ING,Student scores,Categorical,1,0.09647047,1,0.03521779,0.12132822,1,0.02453802,0.09358857,0.04417023,0.11766432,Yes,Yes,No,Proficiency levels in English
22,22,a1,Student questionnaire,Categorical,0.14796867,0.99719956,0.06589631,0.081557,0.06449553,0.04772036,0.05786125,0.05621392,0.01052632,0.00234742,Yes,Yes,No,Sex
31,31,a4,Student questionnaire,Categorical,0.13729809,0.17966298,0.06589631,0.08124807,0.06417625,0.05136778,0.05877007,1,0.09901788,1,Yes,Yes,No,Has repeated one or two times
32,32,repeater,Student questionnaire,Categorical,0.13729809,0.17966298,0.06589631,0.08124807,0.06417625,0.05136778,0.05877007,1,0.09901788,1,Yes,Yes,Yes,Transformation of A4. Has repeated one or more...
150,150,a24,Student questionnaire,Categorical,1,1,1,1,0.08429119,1,1,0.06867214,1,0.07247653,Yes,Yes,No,Studies that I will do next year
155,155,a41,Student questionnaire,Categorical,1,1,1,1,0.06417625,1,1,0.0674567,1,0.0786385,Yes,Yes,No,I repeated in primary education
156,156,a42,Student questionnaire,Categorical,1,1,1,1,0.06417625,1,1,0.06411425,1,0.06983568,Yes,Yes,No,I repeated in secondary education
173,173,country_iso_cnac,Student questionnaire,Categorical,1,1,0.09306683,0.14457831,0.14974457,0.06595745,0.10209028,0.10665451,1,1,Yes,Yes,No,Birth country ISO
174,174,country_iso_nac,Student questionnaire,Categorical,1,1,0.08276077,0.11986407,0.11206897,0.05349544,0.06331415,0.07961106,1,1,Yes,Yes,No,Nationality country ISO
311,311,island,School principals questionnaire,Categorical,0.00107685,0.00478007,0.0003123,0.00185357,0.06417625,0.00607903,0.00151469,0.05621392,0.00377739,0.06132629,Yes,Yes,No,Canary island to which the school belongs
312,312,capital_island,School principals questionnaire,Categorical,0.00107685,0.00478007,0.0003123,0.00185357,0.06417625,0.00607903,0.00151469,0.05621392,0.00377739,0.06132629,Yes,Yes,Yes,Tranformation of island. Capital island vs non...
313,313,public_private,School principals questionnaire,Categorical,0.00107685,0.00478007,0.0003123,0.00185357,0.06417625,0.00607903,0.00151469,0.05621392,0.00377739,0.06132629,Yes,Yes,No,Public or private school
318,318,f3a,Family questionnaire,Categorical,0.33259912,0.30978707,0.52342286,0.4300278,0.11590038,0.13343465,0.13662527,0.09024613,0.41077814,0.1056338,Yes,Yes,No,Mother education level
319,319,f3b,Family questionnaire,Categorical,0.38952521,0.37158998,0.54122423,0.44825456,0.15166028,0.22158055,0.25325659,0.12275904,0.43923445,0.13116197,Yes,Yes,No,Father education level
320,320,mother_education,Family questionnaire,Categorical,0.33259912,0.30978707,0.52342286,0.4300278,0.11590038,0.13343465,0.13662527,0.09024613,0.41077814,0.1056338,Yes,Yes,Yes,Transformation of f3a. Mother education
321,321,father_education,Family questionnaire,Categorical,0.38952521,0.37158998,0.54122423,0.44825456,0.15166028,0.22158055,0.25325659,0.12275904,0.43923445,0.13116197,Yes,Yes,Yes,Transformation of f3b. Father education
322,322,f4a,Family questionnaire,Categorical,0.34517866,0.3258172,0.52810743,0.43929564,0.11685824,0.14589666,0.15268101,0.11759344,0.42493075,0.12265258,Yes,Yes,No,Mother employment status
323,323,f4b,Family questionnaire,Categorical,0.39818894,0.38510936,0.54403498,0.46246525,0.14814815,0.22218845,0.25507422,0.15162565,0.45615714,0.15346244,Yes,Yes,No,Father employment status
324,324,f5a,Family questionnaire,Categorical,0.36686246,0.33861233,0.52841974,0.43466172,0.3087484,0.13130699,0.13420176,0.06593741,0.40261899,0.07159624,Yes,Yes,No,Mother place of birth
325,325,f5b,Family questionnaire,Categorical,0.40861478,0.38385399,0.54184884,0.44794563,0.29885057,0.20303951,0.23235383,0.07687633,0.42140519,0.07775822,Yes,Yes,No,Father place of birth
326,326,f5n,Family questionnaire,Categorical,0.32809594,0.30959394,0.51998751,0.42724745,0.22190294,0.10820669,0.11451075,0.07019143,0.39843868,0.07453052,Yes,Yes,No,Student place of birth
327,327,inmigrant,Family questionnaire,Categorical,0.32809594,0.30959394,0.51998751,0.42724745,0.22190294,0.10820669,0.11451075,0.07019143,0.39843868,0.07453052,Yes,Yes,Yes,Transformation of f5n. Immigrant status
328,328,inmigrant2,Family questionnaire,Categorical,0.32809594,0.30959394,0.51998751,0.42724745,0.22190294,0.10820669,0.11451075,0.07019143,0.39843868,0.07453052,Yes,Yes,Yes,Transformation of f5n. Immigrant status
329,329,inmigrant_second_gen,Family questionnaire,Categorical,0.35521292,0.32601033,0.52654591,0.43280816,0.25031928,0.1212766,0.12178128,0.06198724,0.39889197,0.06748826,Yes,Yes,Yes,"Transformation of f5n. Immigrant status, secon..."
344,344,f11,Family questionnaire,Categorical,0.31600587,0.28912172,0.51623985,0.42168675,0.06417625,0.10121581,0.10996668,0.05894865,0.39632334,0.06338028,Yes,Yes,No,Number of books at home
345,345,books,Family questionnaire,Categorical,0.31600587,0.28912172,0.51623985,0.42168675,0.06417625,0.10121581,0.10996668,0.05894865,0.39632334,0.06338028,Yes,Yes,Yes,Transformation of f11. Number of books at home
385,385,f23,Family questionnaire,Categorical,0.40939794,0.38182608,0.5649594,0.47729379,1,0.10942249,0.11451075,1,0.40141022,1,Yes,Yes,No,Parent expectations: Up to what educational le...
386,386,f24a,Family questionnaire,Categorical,0.34317181,0.32185795,0.51623985,0.42168675,0.15102171,0.19361702,0.19539533,0.19538134,0.45449509,0.20246479,Yes,Yes,No,Mother occupation
387,387,f24b,Family questionnaire,Categorical,0.39344102,0.37448699,0.51623985,0.42168675,0.17688378,0.26382979,0.28173281,0.20601641,0.48557039,0.21390845,Yes,Yes,No,Father occupation
388,388,mother_occupation,Family questionnaire,Categorical,0.34317181,0.32185795,0.51623985,0.42168675,0.15102171,0.19361702,0.19539533,0.19538134,0.45449509,0.20246479,Yes,Yes,Yes,Transformation of f24a. Mother occupation
389,389,father_occupation,Family questionnaire,Categorical,0.39344102,0.37448699,0.51623985,0.42168675,0.17688378,0.26382979,0.28173281,0.20601641,0.48557039,0.21390845,Yes,Yes,Yes,Transformation of f24b. Father occupation
401,401,f34,Family questionnaire,Categorical,1,1,0.51623985,0.42168675,1,0.11246201,0.12541654,1,0.40412994,1,Yes,Yes,No,Monthly household income
402,402,household_income_q,Family questionnaire,Categorical,1,1,0.57682698,0.50139018,1,0.23404255,0.24325962,1,0.48043314,1,Yes,Yes,Yes,Tranformation of f34. Monthly household income...
404,404,ESCS,Family questionnaire,Continuous,0.31649535,0.29013568,0.51623985,0.42168675,0.07758621,0.10972644,0.11481369,0.0793072,0.4064971,0.08568075,Yes,Yes,Yes,"Economic, Social and Cultural Status index"